- name: Install Ansible Prereqs
  hosts: all
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - raw: "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python-minimal python-pip"
